# Generated by Django 4.2.11 on 2024-03-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_categories_options_alter_onsale_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='onsale',
            name='imageUrl',
            field=models.CharField(blank=True, db_column='image_url', default='', max_length=250),
        ),
        migrations.AddField(
            model_name='onsale',
            name='productId',
            field=models.ForeignKey(blank=True, db_column='productId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(blank=True, db_column='categoryId', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='instock',
            field=models.IntegerField(blank=True, db_column='inStock', default=0),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='ordercount',
            field=models.IntegerField(blank=True, db_column='orderCount', default=0),
        ),
        migrations.AlterField(
            model_name='onsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='instock',
            field=models.IntegerField(blank=True, db_column='inStock', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordercount',
            field=models.IntegerField(blank=True, db_column='orderCount', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.TextField(blank=True, db_column='imageUrl', default=''),
        ),
    ]
