# Generated by Django 4.2.11 on 2024-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_onsale_image_url_remove_product_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.TextField(db_column='imageUrl', default=''),
        ),
    ]
