# Generated by Django 4.2.11 on 2024-04-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0004_alter_product_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('imageUrl', models.TextField(db_column='imageUrl', default='')),
                ('date_added', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favProducts',
            },
        ),
    ]
