# Generated by Django 4.2.11 on 2024-04-08 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_favproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favproduct',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='favproduct',
            old_name='user',
            new_name='userId',
        ),
    ]
