# Generated by Django 4.2.11 on 2024-04-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0006_alter_favproduct_user_rename_user_favproduct_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='instock',
            new_name='inStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ordercount',
            new_name='orderCount',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('imageUrl', models.TextField(db_column='imageUrl', default='')),
                ('date_added', models.DateField()),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
